services:
  client:
    build:
      context: ./client
      dockerfile: build/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: build/Dockerfile
    ports:
      - "8000:8000"
